# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/minyt',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/minyt',
                'lib_path': 'minyt'},
  'syms': {'minyt.core': {'minyt.core.foo': ('core.html#foo', 'minyt/core.py')}}}
